services:
  cfwg:
    image: ghcr.io/crazy0x70/cfwg:latest
    container_name: cfwg
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0"
    tmpfs:
      - /tmp
      - /run
    ports:
      - "127.0.0.1:1080:1080/tcp"
      - "127.0.0.1:1080:1080/udp"
    environment:
      PROXY_PUBLIC_HOST: 127.0.0.1
      PROXY_PUBLIC_PORT: 1080
    volumes:
      - ./data:/var/lib/warp-socks
    networks:
      - default

networks:
  default:
    name: cfwg
